/***********************************************************************************************************************
 * This file was generated by the S32 Config Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef lpuart_LPUART_1_H
#define lpuart_LPUART_1_H

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 *
 */
/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "lpuart_driver.h"

/*******************************************************************************
 * Definitions 
 ******************************************************************************/
#define INST_LPUART_LPUART_0  0
/* Receive buffer size */
#define BUFFER_SIZE 256U

/* External declaration of LPUART configuration structure */
extern const lpuart_user_config_t lpUartInitConfig1;

extern lpuart_state_t lpUartState1;

extern uint8_t tr0_idx;
extern uint8_t tr0_buf[BUFFER_SIZE];
extern uint8_t tr0_2ms;

extern uint8_t tx0_idx;
extern uint8_t tx0_length;
extern uint8_t tx0_buf[BUFFER_SIZE];
extern uint8_t tx0_2ms;

void Init_Uart(void);
void rxCallback(void *driverState, uart_event_t event, void *userData);
void txCallback(void *driverState, uart_event_t event, void *userData);
void start_tx(uint8_t len);



#endif /* lpuart_LPUART_1_H */
